<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  /*
   * Deliberately plain literal colours, not var(--x) - dompdf's CSS
   * support is a fixed subset (no flexbox, unreliable custom
   * properties, no partial-arc SVG), so this template doesn't share
   * code with the web views. It shares only the look: same palette,
   * same "counts, not an invented score" rule, same voice.
   */
  body{ font-family: DejaVu Sans, sans-serif; font-size: 11px; color:#1a1a1a; margin:0; }
  .header{ padding-bottom:14px; border-bottom:2px solid #E1691F; margin-bottom:18px; }
  .header img{ height:32px; }
  .header .title{ font-size:20px; font-weight:bold; margin-top:10px; }
  .header .url{ font-size:12px; color:#555; font-family: DejaVu Sans Mono, monospace; margin-top:2px; }
  .header .meta{ font-size:10px; color:#777; margin-top:4px; }

  .counts{ margin:16px 0 20px; }
  .counts td{ padding:10px 16px; border-radius:4px; text-align:center; font-size:13px; font-weight:bold; }
  .c-fail{ background:#FBE5E3; color:#C0392B; }
  .c-warn{ background:#FCEEDA; color:#B8720C; }
  .c-pass{ background:#E3F6EC; color:#1E8A5A; }
  .spacer{ width:12px; }

  h2{ font-size:14px; margin:22px 0 8px; border-bottom:1px solid #ddd; padding-bottom:4px; }

  .lh-table{ width:100%; border-collapse:collapse; margin-top:6px; }
  .lh-table td{ text-align:center; padding:10px; width:25%; }
  .lh-table .num{ font-size:22px; font-weight:bold; }
  .lh-table .label{ font-size:10px; color:#555; margin-top:2px; }
  .lh-good{ color:#1E8A5A; }
  .lh-fair{ color:#B8720C; }
  .lh-poor{ color:#C0392B; }
  .vitals{ font-size:10px; color:#555; margin-top:8px; }

  .recommendations{ font-size:11px; line-height:1.6; background:#FAF6F1; border:1px solid #EEDFCF; padding:14px; border-radius:4px; }

  .finding{ padding:8px 0; border-bottom:1px solid #eee; }
  .finding .ftitle{ font-weight:bold; font-size:11.5px; }
  .finding .fdetail{ color:#555; font-size:10.5px; margin-top:2px; }
  .tag{ display:inline-block; font-size:8.5px; font-weight:bold; padding:2px 6px; border-radius:3px; margin-right:6px; }

  .footer{ margin-top:26px; padding-top:10px; border-top:1px solid #ddd; font-size:9px; color:#999; }
</style>
</head>
<body>

  <div class="header">
    <img src="{{ public_path('assets/synthseo-logo.png') }}">
    <div class="title">{{ $audit->site->name }} — SEO Audit</div>
    <div class="url">{{ $audit->url }}</div>
    <div class="meta">{{ $audit->created_at->format('j F Y, H:i') }} &middot; HTTP {{ $audit->http_status }} &middot; {{ $audit->response_ms }}ms response</div>
  </div>

  @php
    $counts = $audit->issueCounts();
  @endphp
  <table class="counts" width="100%">
    <tr>
      <td class="c-fail">{{ $counts['fail'] }} to fix</td>
      <td class="spacer"></td>
      <td class="c-warn">{{ $counts['warn'] }} to review</td>
      <td class="spacer"></td>
      <td class="c-pass">{{ $counts['pass'] }} passing</td>
    </tr>
  </table>

  @if ($audit->recommendations)
    <h2>AI recommendations</h2>
    <div class="recommendations">{{ $audit->recommendations }}</div>
  @endif

  @if ($audit->hasLighthouse())
    <h2>Site performance</h2>
    <table class="lh-table">
      <tr>
        @foreach ([
          'Performance' => $audit->lh_performance,
          'SEO' => $audit->lh_seo,
          'Accessibility' => $audit->lh_accessibility,
          'Best practices' => $audit->lh_best_practices,
        ] as $label => $value)
          <td>
            <div class="num lh-{{ \App\Models\Audit::lighthouseBand($value) }}">{{ $value !== null ? $value : '-' }}</div>
            <div class="label">{{ $label }}</div>
          </td>
        @endforeach
      </tr>
    </table>
    <div class="vitals">
      @if ($audit->lh_lcp_ms !== null)
        <span class="lh-{{ \App\Models\Audit::lcpBand($audit->lh_lcp_ms) }}">Main content loads in {{ number_format($audit->lh_lcp_ms / 1000, 1) }}s</span> &nbsp;
      @endif
      @if ($audit->lh_tbt_ms !== null)
        <span class="lh-{{ \App\Models\Audit::tbtBand($audit->lh_tbt_ms) }}">Page unresponsive for {{ $audit->lh_tbt_ms }}ms while loading</span> &nbsp;
      @endif
      @if ($audit->lh_cls !== null)
        <span class="lh-{{ \App\Models\Audit::clsBand($audit->lh_cls) }}">Visual stability {{ rtrim(rtrim(number_format($audit->lh_cls, 3), '0'), '.') ?: '0' }}</span>
      @endif
    </div>
  @endif

  <h2>Findings</h2>
  @foreach ($findings as $finding)
    <div class="finding">
      <span class="tag c-{{ $finding->status }}">{{ strtoupper($finding->status) }}</span>
      <span class="ftitle">{{ $finding->title }}</span>
      @if ($finding->detail)<div class="fdetail">{{ $finding->detail }}</div>@endif
    </div>
  @endforeach

  <div class="footer">Generated by SynthSEO &middot; synthseo.co.uk</div>

</body>
</html>
